name: CI

on:
  push:
    tags:
      - "**"
    branches:
      - main

env:
  BB_CI: 1
  BUILD_DEBUG: 1

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        BIRTH_CMAKE_BUILD_TYPES: [ Debug, Release-assertions, Release ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and test (Packaged LLVM)
        shell: bash
        env:
          BB_CI: 1
          CMAKE_BUILD_TYPE: ${{matrix.BIRTH_CMAKE_BUILD_TYPES}}
          CLANG_PATH: clang-19
          CLANGXX_PATH: clang++-19
        run: |
          set -eux
          ci/reproduce.sh
  release:
    needs: ci
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        shell: bash
        env:
          BB_CI: 1
        run: |
          set -eux
          ci/install.sh
      - name: Release (locally)
        if: ${{ (github.ref == 'refs/heads/main') }}
        shell: bash
        env:
          BB_CI: 1
        run: |
          set -eux
          ci/release.sh
      - name: Release (web)
        uses: akkuman/gitea-release-action@v1
        if: ${{ (github.ref == 'refs/heads/main') }}
        env:
          NODE_OPTIONS: '--experimental-fetch' # if nodejs < 18
        with:
          files: |-
            /home/act_runner/bloat-buster-artifacts/releases/main/compiler_generic_debug
            /home/act_runner/bloat-buster-artifacts/releases/main/compiler_generic
            /home/act_runner/bloat-buster-artifacts/releases/main/compiler_native
