name: CI

on:
  pull_request:

env:
  BB_CI: 1

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        BIRTH_CMAKE_BUILD_TYPE: [ Release-assertions, Release ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and test (Packaged LLVM)
        shell: bash
        env:
          BB_CI: 1
          CMAKE_BUILD_TYPE: ${{matrix.BIRTH_CMAKE_BUILD_TYPE}}
          CLANG_PATH: clang-19
          CLANGXX_PATH: clang++-19
        run: |
          set -eux
          ./generate.sh
          ./build.sh
          ./build/bb test
