#include <lib.h>

#ifdef _WIN32
typedef f64 FloatLiteral;
#else
typedef f128 FloatLiteral;
#endif

typedef enum TokenId : u8
{
    TOKEN_ID_NONE,

    TOKEN_ID_IDENTIFIER,
    TOKEN_ID_INTEGER,
    TOKEN_ID_FLOAT,
    TOKEN_ID_FLOAT_STRING_LITERAL,
    TOKEN_ID_STRING_LITERAL,
    TOKEN_ID_CHARACTER_LITERAL,

    TOKEN_ID_KEYWORD_TYPE_INTEGER,
    TOKEN_ID_KEYWORD_TYPE_FLOAT,

    TOKEN_ID_KEYWORD_TYPE,
    TOKEN_ID_KEYWORD_TYPE_VOID,
    TOKEN_ID_KEYWORD_TYPE_NORETURN,
    TOKEN_ID_KEYWORD_TYPE_ENUM,
    TOKEN_ID_KEYWORD_TYPE_STRUCT,
    TOKEN_ID_KEYWORD_TYPE_BITS,
    TOKEN_ID_KEYWORD_TYPE_UNION,
    TOKEN_ID_KEYWORD_TYPE_FN,
    TOKEN_ID_KEYWORD_TYPE_ALIAS,
    TOKEN_ID_KEYWORD_TYPE_VECTOR,
    TOKEN_ID_KEYWORD_TYPE_ENUM_ARRAY,
    TOKEN_ID_KEYWORD_TYPE_OPAQUE,

    TOKEN_ID_KEYWORD_STATEMENT_UNDERSCORE,
    TOKEN_ID_KEYWORD_STATEMENT_RETURN,
    TOKEN_ID_KEYWORD_STATEMENT_IF,
    TOKEN_ID_KEYWORD_STATEMENT_WHEN,
    TOKEN_ID_KEYWORD_STATEMENT_FOR,
    TOKEN_ID_KEYWORD_STATEMENT_WHILE,
    TOKEN_ID_KEYWORD_STATEMENT_SWITCH,
    TOKEN_ID_KEYWORD_STATEMENT_BREAK,
    TOKEN_ID_KEYWORD_STATEMENT_CONTINUE,
    TOKEN_ID_KEYWORD_STATEMENT_UNREACHABLE,
    TOKEN_ID_KEYWORD_STATEMENT_ELSE,

    TOKEN_ID_KEYWORD_VALUE_UNDEFINED,
    TOKEN_ID_KEYWORD_VALUE_ZERO,

    TOKEN_ID_KEYWORD_OPERATOR_AND,
    TOKEN_ID_KEYWORD_OPERATOR_OR,
    TOKEN_ID_KEYWORD_OPERATOR_AND_SHORTCIRCUIT,
    TOKEN_ID_KEYWORD_OPERATOR_OR_SHORTCIRCUIT,

    TOKEN_ID_ASSIGN,
    TOKEN_ID_COMPARE_EQUAL,
    TOKEN_ID_SWITCH_CASE,

    TOKEN_ID_EXCLAMATION_DOWN,
    TOKEN_ID_COMPARE_NOT_EQUAL,

    TOKEN_ID_COMPARE_LESS,
    TOKEN_ID_COMPARE_LESS_EQUAL,
    TOKEN_ID_SHIFT_LEFT,
    TOKEN_ID_SHIFT_LEFT_ASSIGN,

    TOKEN_ID_COMPARE_GREATER,
    TOKEN_ID_COMPARE_GREATER_EQUAL,
    TOKEN_ID_SHIFT_RIGHT,
    TOKEN_ID_SHIFT_RIGHT_ASSIGN,

    TOKEN_ID_PLUS,
    TOKEN_ID_ADD_ASSIGN,

    TOKEN_ID_DASH,
    TOKEN_ID_SUB_ASSIGN,

    TOKEN_ID_ASTERISK,
    TOKEN_ID_MUL_ASSIGN,

    TOKEN_ID_FORWARD_SLASH,
    TOKEN_ID_DIV_ASSIGN,

    TOKEN_ID_PERCENTAGE,
    TOKEN_ID_REM_ASSIGN,

    TOKEN_ID_AMPERSAND,
    TOKEN_ID_BITWISE_AND_ASSIGN,

    TOKEN_ID_BAR,
    TOKEN_ID_BITWISE_OR_ASSIGN,

    TOKEN_ID_CARET,
    TOKEN_ID_BITWISE_XOR_ASSIGN,

    TOKEN_ID_DOT,
    TOKEN_ID_POINTER_DEREFERENCE,
    TOKEN_ID_OPTIONAL_DEREFERENCE,
    TOKEN_ID_DOUBLE_DOT,
    TOKEN_ID_TRIPLE_DOT,

    TOKEN_ID_LEFT_PARENTHESIS,
    TOKEN_ID_RIGHT_PARENTHESIS,
    TOKEN_ID_LEFT_BRACE,
    TOKEN_ID_RIGHT_BRACE,
    TOKEN_ID_LEFT_BRACKET,
    TOKEN_ID_RIGHT_BRACKET,

    TOKEN_ID_COMMA,
    TOKEN_ID_SEMICOLON,
    TOKEN_ID_COLON,
    TOKEN_ID_QUESTION,
    TOKEN_ID_AT,
    TOKEN_ID_BACKTICK,
    TOKEN_ID_BACKSLASH,
    TOKEN_ID_HASH,
    TOKEN_ID_DOLLAR,
    TOKEN_ID_TILDE,

    TOKEN_COUNT,
} TokenId;

STRUCT(TokenIntegerType)
{
    u64 bit_count;
    bool is_signed;
};

UNION(TokenContent)
{
    str string;
    u128 integer;
    FloatLiteral float_literal;
    TokenIntegerType integer_type;
};

STRUCT(Token)
{
    u8 type;
    u8 tag;
};

STRUCT(TokenList)
{
    Token* pointer;
    u64 length;
};

typedef enum LexerErrorId
{
    LEXER_ERROR_ID_NONE,
    LEXER_ERROR_ID_LINE_NUMBER_TOO_HIGH,
    LEXER_ERROR_ID_COLUMN_NUMBER_TOO_HIGH,
    LEXER_ERROR_ID_PRIMITIVE_TYPE_0_BIT_COUNT,
    LEXER_ERROR_ID_PRIMITIVE_TYPE_UNKNOWN_BIT_COUNT,
    LEXER_ERROR_ID_STRING_LITERAL_NO_DOUBLE_QUOTE_EOF,
    LEXER_ERROR_ID_CHARACTER_LITERAL_EMPTY,
    LEXER_ERROR_ID_CHARACTER_LITERAL_BADLY_TERMINATED,
    LEXER_ERROR_ID_NOT_SUPPORTED_X_ASCII_OR_UNICODE,
    LEXER_ERROR_ID_NON_PRINTABLE_ASCII,
    LEXER_ERROR_ID_FOUND_DEL,
    LEXER_ERROR_ID_IDENTIFIER_TOO_LONG,
} LexerErrorId;

STRUCT(LexerError)
{
    u64 offset;
    u32 line;
    u32 column;
    LexerErrorId id;
};

EXPORT TokenList lex(Arena* stable_arena, Arena* else_arena, const char* restrict p, u64 l, LexerError* error_list);
