name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  linux_build_and_test:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and test
        run: |
          ./run_tests.sh
  # macos_build_and_test:
  #   runs-on: macos-latest
  #   timeout-minutes: 15
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Build and test
  #       run: |
  #         ./run_tests.sh
