name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

env:
  TIMEOUT_MINUTES: 15
jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and test
        run: |
          set -ex
          ./run_tests.sh
