name: CI

on:
  push:
    tags:
      - "**"
    branches:
      - main

env:
  BB_CI: 1
  LLVM_VERSION: 20.1.7
  CLANG_PATH: clang-19
  CLANGXX_PATH: clang++-19
  BB_CACHE_DIR: bb-cache

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ self-hosted ]
        BIRTH_CMAKE_BUILD_TYPE: [ Release-assertions, Release ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and test (Packaged LLVM)
        shell: bash
        env:
          CMAKE_BUILD_TYPE: ${{matrix.BIRTH_CMAKE_BUILD_TYPE}}
        run: |
          set -eux
          ci/reproduce.sh
  release:
    needs: ci
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        os: [ self-hosted ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        shell: bash
        env:
          BB_CI: 1
        run: |
          set -eux
          ci/install.sh
      - name: Release (locally)
        if: ${{ (github.ref == 'refs/heads/main') }}
        shell: bash
        env:
          BB_CI: 1
        run: |
          set -eux
          ci/release.sh
      - name: Create tag
        if: github.ref == 'refs/heads/main'
        shell: bash
        id: generate-tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -eux
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          TAG="dev"
          git tag -d $TAG || true
          git push origin --delete $TAG || true
          git fetch --tags
          git tag -l
          git tag $TAG
          git push origin $TAG
          echo "RELEASE_TAG_NAME=$TAG" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ (github.ref == 'refs/heads/main') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG_NAME }}
          name: "Development build"
          fail_on_unmatched_files: true
          make_latest: true
          draft: false
          files: |
            /home/act_runner/bloat-buster-artifacts/releases/main/compiler_generic
            /home/act_runner/bloat-buster-artifacts/releases/main/compiler_native
