name: CI

on:
  pull_request:

env:
  BB_CI: 1
  CLANG_PATH: clang-19
  CLANGXX_PATH: clang++-19
  LLVM_VERSION: 21.1.1
  BB_CACHE_DIR: bb-cache

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ self-hosted ]
        BIRTH_CMAKE_BUILD_TYPE: [ Debug, Release ]
        LLVM_CMAKE_BUILD_TYPE: [ Release, Release-assertions ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and test (Packaged LLVM)
        shell: bash
        env:
          CMAKE_BUILD_TYPE: ${{matrix.BIRTH_CMAKE_BUILD_TYPE}}
          LLVM_CMAKE_BUILD_TYPE: ${{matrix.LLVM_CMAKE_BUILD_TYPE}}
        run: |
          set -eux
          ./generate.sh
          ./build.sh
          ./build/bb
