name: CI

on:
  pull_request:

env:
  BB_CI: 1
  CLANG_PATH: clang-19
  CLANGXX_PATH: clang++-19
  LLVM_VERSION: 20.1.7
  BB_CACHE_DIR: bb-cache

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ self-hosted ]
        BIRTH_CMAKE_BUILD_TYPE: [ Release-assertions, Release ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and test (Packaged LLVM)
        shell: bash
        env:
          CMAKE_BUILD_TYPE: ${{matrix.BIRTH_CMAKE_BUILD_TYPE}}
        run: |
          set -eux
          ./generate.sh
          CMAKE_PREFIX_PATH=$HOME/dev/llvm/install/llvm_${LLVM_VERSION}_x86_64-linux-${CMAKE_BUILD_TYPE} $HOME/bloat-buster-artifacts/releases/main/compiler_generic_debug compile src/compiler.bbb
          bb-cache/debug_none_di_native/compiler reproduce
